package com.ericduffy.raybanautomation

import android.Manifest
import android.content.pm.PackageManager
import android.os.Bundle
import android.widget.Button
import android.widget.Toast
import androidx.activity.result.contract.ActivityResultContracts
import androidx.appcompat.app.AppCompatActivity
import androidx.core.content.ContextCompat
import com.facebook.wearable.dat.android.Wearables

class MainActivity : AppCompatActivity() {

    private lateinit var callManager: CallManager

    private val permissionLauncher = registerForActivityResult(
        ActivityResultContracts.RequestMultiplePermissions()
    ) { permissions ->
        val allGranted = permissions.entries.all { it.value }
        if (allGranted) {
            setupUI()
            handleIntent(intent)
        } else {
            Toast.makeText(this, "Permissions required for functionality", Toast.LENGTH_LONG).show()
        }
    }

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main) // Note: layout file not created yet, usually auto-generated by wizard but we skipped it.

        // Fix: We need to create a simple layout programmatically or ignore layout if using Compose.
        // For simplicity in this text-based env, I'll assume usage of basic views or create logic directly.
        // But to be correct I need to creating the 'activity_main.xml' or just use code-based UI for now.
        // Let's create a programmatic UI for simplicity.
        createProgrammaticUI()

        callManager = CallManager(this)

        // Initialize Meta Wearables SDK
        try {
            Wearables.initialize(this)
        } catch(e: Exception) {
             // Handle if SDK is missing or fails
             e.printStackTrace()
        }

        checkAndRequestPermissions()
    }

    private fun createProgrammaticUI() {
        val layout = android.widget.LinearLayout(this).apply {
            orientation = android.widget.LinearLayout.VERTICAL
            gravity = android.view.Gravity.CENTER
            setPadding(32, 32, 32, 32)
        }

        val btnCallWife = Button(this).apply {
            text = getString(R.string.btn_call_wife)
            setOnClickListener { callManager.callWifeWhatsApp() }
        }
        
        val btnOpenGate = Button(this).apply {
            text = getString(R.string.btn_open_gate)
            setOnClickListener { callManager.callGate() }
        }

        layout.addView(btnCallWife)
        layout.addView(btnOpenGate)
        setContentView(layout)
    }

    private fun checkAndRequestPermissions() {
        val permissions = arrayOf(
            Manifest.permission.READ_CONTACTS,
            Manifest.permission.CALL_PHONE,
            Manifest.permission.BLUETOOTH_CONNECT,
            Manifest.permission.BLUETOOTH_SCAN
        )

        val missing = permissions.filter {
            ContextCompat.checkSelfPermission(this, it) != PackageManager.PERMISSION_GRANTED
        }

        if (missing.isNotEmpty()) {
            permissionLauncher.launch(missing.toTypedArray())
        } else {
            setupUI() // UI is always set up, but this could trigger ready-state logic
            handleIntent(intent)
        }
    }

    private fun setupUI() {
        // Any specific UI enabling logic if buttons were disabled initially
    }

    private fun handleIntent(intent: android.content.Intent?) {
        intent?.let {
            when (it.action) {
                "com.ericduffy.raybanautomation.ACTION_CALL_WIFE" -> {
                    callManager.callWifeWhatsApp()
                    finish() // Close app after triggering action? Or keep open?
                }
                "com.ericduffy.raybanautomation.ACTION_OPEN_GATE" -> {
                    callManager.callGate()
                    finish()
                }
                else -> {
                    // Normal launch
                }
            }
        }
    }
}
